In [14]:
import json
import pandas as pd
pd.set_option('display.max_columns', None)

In [28]:
def create_df_from_json_file(filename: str) -> pd.core.frame.DataFrame:
    with open(filename) as f:
        lines = f.read().split("\n")
    
    entities = []
    for line in lines:
        try:
            entities.append(json.loads(line))
        except Exception as error:
            print(error)
            continue
    df = pd.DataFrame(entities)
    df = df.set_index("id")
    return df

def create_df_for_label_file(filename: str, label_colname: str) -> pd.core.frame.DataFrame:
    with open(filename) as f:
        json_object = json.load(f)
    df = pd.DataFrame({"id": list(json_object.keys()), label_colname: list(json_object.values())})
    df["id"] = df["id"].astype(int)
    df = df.set_index("id")
    return df

In [29]:
df_training_set = create_df_from_json_file("2_training_set.json")
df_training_anno_top = create_df_for_label_file("2_training_anno_top.json", "label_top")
df_training_anno_mid = create_df_for_label_file("2_training_anno_mid.json", "label_mid")
df_training_anno_fine = create_df_for_label_file("2_training_anno_fine.json", "label_fine")

Expecting value: line 1 column 1 (char 0)

In [30]:
df_training_set

,pr,rev_intervals_ccnt,rev_pld_max,dst_port,num_pkts_in,pld_ccnt,rev_hdr_ccnt,rev_pld_ccnt,hdr_mean,rev_hdr_bin_40,bytes_in,rev_ack_psh_rst_syn_fin_cnt,time_length,da,rev_pld_var,pld_mean,rev_pld_mean,pld_median,src_port,rev_pld_bin_128,sa,hdr_distinct,rev_pld_distinct,ack_psh_rst_syn_fin_cnt,pld_distinct,rev_hdr_distinct,hdr_bin_40,intervals_ccnt,pld_bin_inf,num_pkts_out,hdr_ccnt,bytes_out,pld_max,tls_svr_key_exchange_len,tls_svr_cs_cnt,tls_key_exchange_len,tls_svr_ext_cnt,tls_svr_ext_types,tls_ext_cnt,tls_svr_cs,tls_ext_types,tls_len,tls_svr_len,tls_cs_cnt,tls_svr_cnt,tls_cs,tls_cnt,dns_query_name,dns_query_cnt,dns_query_name_len,dns_query_type,dns_query_class,dns_answer_cnt,dns_answer_ttl,dns_answer_ip,http_uri,http_content_type,http_content_len,http_host,http_code,http_method
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
8128279,17,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0,5355,0,"[2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",8.00,0,0,"[0, 0, 0, 0, 0]",0.412089,IP_masked,0.00,22.00,0.00,22,50028,0,IP_masked,1,0,"[0, 0, 0, 0, 0]",1,0,0,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0,2,"[2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",44,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1060911,6,"[0, 0, 0, 0, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 0]",0,443,13,"[13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",20.00,0,0,"[13, 0, 0, 0, 0]",360.001580,IP_masked,0.00,6.00,0.00,6,13404,13,IP_masked,1,1,"[13, 13, 0, 0, 0]",1,1,0,"[0, 0, 0, 0, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 0]",0,13,"[0, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",78,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8338242,17,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0,5355,0,"[2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",8.00,0,0,"[0, 0, 0, 0, 0]",0.411696,IP_masked,0.00,22.00,0.00,22,59764,0,IP_masked,1,0,"[0, 0, 0, 0, 0]",1,0,0,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0,2,"[2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",44,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8067075,6,"[0, 0, 0, 0, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 0]",0,443,13,"[13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",20.00,0,0,"[13, 0, 0, 0, 0]",360.002498,IP_masked,0.00,6.00,0.00,6,13397,13,IP_masked,1,1,"[13, 13, 0, 0, 0]",1,1,0,"[0, 0, 0, 0, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 0]",0,13,"[0, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",78,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3497215,6,"[12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",1350,13000,13,"[7, 0, 1, 0, 1, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 5]","[0, 12, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]","[5, 0, 0, 1, 1, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 3]",20.71,1,5828,"[13, 6, 0, 1, 1]",0.109800,IP_masked,520.37,489.41,448.31,302,13411,5,IP_masked,2,7,"[16, 6, 0, 1, 1]",8,2,1,"[16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",5,17,"[0, 16, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]",8320,1350,0.0,1.0,130.0,2.0,"[ff01, 0023]",4.0,[009d],"[000b, 000a, 0023, 000d]","[501, 134, 1, 3130, 424, 297, 3753]","[53, 2695, 371, 298, 425]",80.0,5.0,"[c030, c02c, c028, c024, c014, c00a, c022, c02...",7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2474371,17,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",379,53,1,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",8.00,0,379,"[0, 0, 0, 0, 0]",0.000000,IP_masked,0.00,33.00,379.00,33,3050,0,IP_masked,1,1,"[0, 0, 0, 0, 0]",1,1,0,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0,1,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",33,33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[www.youtube.com],1.0,[15],[1],[1],12.0,"[76582, 158, 158, 158, 158, 158, 158, 158, 158...","[, 173.194.123.104, 173.194.123.105, 173.194.1...",NaN,NaN,NaN,NaN,NaN,NaN
6706471,17,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",246,53,1,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",8.00,0,246,"[0, 0, 0, 0, 0]",0.000000,IP_masked,0.00,54.00,246.00,54,41673,0,IP_masked,1,1,"[0, 0, 0, 0, 0]",1,1,0,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0,1,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",54,54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[r4---sn-j5o5gpx-t0ae.googlevideo.com],1.0,[36],[1],[1],2.0,"[1021, 1021]","[, 199.212.24.175]",NaN,NaN,NaN,NaN,NaN,NaN
654351,17,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",219,53,1,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",8.00,0,219,"[0, 0, 0, 0, 0]",0.000000,IP_masked,0.00,33.00,219.00,33,49928,0,IP_masked,1,1,"[0, 0, 0, 0, 0]",1,1,0,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0,1,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",33,33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[www.youtube.com],1.0,[15],[1],[1],2.0,"[2622, 268]","[, 216.58.219.238]",NaN,NaN,NaN,NaN,NaN,NaN
3107488,17,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0,137,0,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",8.00,0,0,"[0, 0, 0, 0, 0]",0.000000,IP_masked,0.00,50.00,0.00,50,137,0,IP_masked,1,0,"[0, 0, 0, 0, 0]",1,0,0,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0,1,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",50,50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4900746,17,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",235,53,1,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",8.00,0,235,"[0, 0, 0, 0, 0]",0.000000,IP_masked,0.00,31.00,235.00,31,27012,0,IP_masked,1,1,"[0, 0, 0, 0, 0]",1,1,0,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0,1,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",31,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[yt3.ggpht.com],1.0,[13],[1],[1],2.0,"[588971, 228]","[, 216.58.219.225]",NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
df_training_anno_top

             label_top
id
3145728          audio
2                audio
1354411  file_transfer
7864325          audio
8975141  file_transfer
...                ...
2097141          audio
6553590          audio
3189417  file_transfer
4980731          video
9175037          audio

[131065 rows x 1 columns]

In [32]:
df_training_anno_mid

        label_mid
id
3145728     skype
2        hangouts
1354411     skype
7864325     skype
8975141     skype
...           ...
2097141     skype
6553590  facebook
3189417     skype
4980731   youtube
9175037  hangouts

[131065 rows x 1 columns]

In [33]:
df_training_anno_fine

             label_fine
id
3145728     skype_audio
2        hangouts_audio
1354411      skype_file
7864325     skype_audio
8975141      skype_file
...                 ...
2097141     skype_audio
6553590  facebook_audio
3189417      skype_file
4980731         youtube
9175037  hangouts_audio

[131065 rows x 1 columns]

In [37]:
df_all = df_training_set.join(df_training_anno_top).join(df_training_anno_mid).join(df_training_anno_fine)
df_all

,pr,rev_intervals_ccnt,rev_pld_max,dst_port,num_pkts_in,pld_ccnt,rev_hdr_ccnt,rev_pld_ccnt,hdr_mean,rev_hdr_bin_40,bytes_in,rev_ack_psh_rst_syn_fin_cnt,time_length,da,rev_pld_var,pld_mean,rev_pld_mean,pld_median,src_port,rev_pld_bin_128,sa,hdr_distinct,rev_pld_distinct,ack_psh_rst_syn_fin_cnt,pld_distinct,rev_hdr_distinct,hdr_bin_40,intervals_ccnt,pld_bin_inf,num_pkts_out,hdr_ccnt,bytes_out,pld_max,tls_svr_key_exchange_len,tls_svr_cs_cnt,tls_key_exchange_len,tls_svr_ext_cnt,tls_svr_ext_types,tls_ext_cnt,tls_svr_cs,tls_ext_types,tls_len,tls_svr_len,tls_cs_cnt,tls_svr_cnt,tls_cs,tls_cnt,dns_query_name,dns_query_cnt,dns_query_name_len,dns_query_type,dns_query_class,dns_answer_cnt,dns_answer_ttl,dns_answer_ip,http_uri,http_content_type,http_content_len,http_host,http_code,http_method,label_top,label_mid,label_fine
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
8128279,17,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0,5355,0,"[2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",8.00,0,0,"[0, 0, 0, 0, 0]",0.412089,IP_masked,0.00,22.00,0.00,22,50028,0,IP_masked,1,0,"[0, 0, 0, 0, 0]",1,0,0,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0,2,"[2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",44,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chat,aim,aim_chat
1060911,6,"[0, 0, 0, 0, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 0]",0,443,13,"[13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",20.00,0,0,"[13, 0, 0, 0, 0]",360.001580,IP_masked,0.00,6.00,0.00,6,13404,13,IP_masked,1,1,"[13, 13, 0, 0, 0]",1,1,0,"[0, 0, 0, 0, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 0]",0,13,"[0, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",78,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chat,aim,aim_chat
8338242,17,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0,5355,0,"[2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",8.00,0,0,"[0, 0, 0, 0, 0]",0.411696,IP_masked,0.00,22.00,0.00,22,59764,0,IP_masked,1,0,"[0, 0, 0, 0, 0]",1,0,0,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0,2,"[2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",44,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chat,aim,aim_chat
8067075,6,"[0, 0, 0, 0, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 0]",0,443,13,"[13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",20.00,0,0,"[13, 0, 0, 0, 0]",360.002498,IP_masked,0.00,6.00,0.00,6,13397,13,IP_masked,1,1,"[13, 13, 0, 0, 0]",1,1,0,"[0, 0, 0, 0, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 0]",0,13,"[0, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",78,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chat,aim,aim_chat
3497215,6,"[12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",1350,13000,13,"[7, 0, 1, 0, 1, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 5]","[0, 12, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]","[5, 0, 0, 1, 1, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 3]",20.71,1,5828,"[13, 6, 0, 1, 1]",0.109800,IP_masked,520.37,489.41,448.31,302,13411,5,IP_masked,2,7,"[16, 6, 0, 1, 1]",8,2,1,"[16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",5,17,"[0, 16, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]",8320,1350,0.0,1.0,130.0,2.0,"[ff01, 0023]",4.0,[009d],"[000b, 000a, 0023, 000d]","[501, 134, 1, 3130, 424, 297, 3753]","[53, 2695, 371, 298, 425]",80.0,5.0,"[c030, c02c, c028, c024, c014, c00a, c022, c02...",7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chat,aim,aim_chat
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2474371,17,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",379,53,1,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",8.00,0,379,"[0, 0, 0, 0, 0]",0.000000,IP_masked,0.00,33.00,379.00,33,3050,0,IP_masked,1,1,"[0, 0, 0, 0, 0]",1,1,0,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0,1,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",33,33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[www.youtube.com],1.0,[15],[1],[1],12.0,"[76582, 158, 158, 158, 158, 158, 158, 158, 158...","[, 173.194.123.104, 173.194.123.105, 173.194.1...",NaN,NaN,NaN,NaN,NaN,NaN,video,youtube,youtube
6706471,17,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",246,53,1,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",8.00,0,246,"[0, 0, 0, 0, 0]",0.000000,IP_masked,0.00,54.00,246.00,54,41673,0,IP_masked,1,1,"[0, 0, 0, 0, 0]",1,1,0,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0,1,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",54,54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[r4---sn-j5o5gpx-t0ae.googlevideo.com],1.0,[36],[1],[1],2.0,"[1021, 1021]","[, 199.212.24.175]",NaN,NaN,NaN,NaN,NaN,NaN,video,youtube,youtube
654351,17,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",219,53,1,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",8.00,0,219,"[0, 0, 0, 0, 0]",0.000000,IP_masked,0.00,33.00,219.00,33,49928,0,IP_masked,1,1,"[0, 0, 0, 0, 0]",1,1,0,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0,1,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",33,33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[www.youtube.com],1.0,[15],[1],[1],2.0,"[2622, 268]","[, 216.58.219.238]",NaN,NaN,NaN,NaN,NaN,NaN,video,youtube,youtube
3107488,17,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0,137,0,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",8.00,0,0,"[0, 0, 0, 0, 0]",0.000000,IP_masked,0.00,50.00,0.00,50,137,0,IP_masked,1,0,"[0, 0, 0, 0, 0]",1,0,0,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0,1,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",50,50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,video,youtube,youtube
4900746,17,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",235,53,1,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",8.00,0,235,"[0, 0, 0, 0, 0]",0.000000,IP_masked,0.00,31.00,235.00,31,27012,0,IP_masked,1,1,"[0, 0, 0, 0, 0]",1,1,0,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",0,1,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",31,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[yt3.ggpht.com],1.0,[13],[1],[1],2.0,"[588971, 228]","[, 216.58.219.225]",NaN,NaN,NaN,NaN,NaN,NaN,video,youtube,youtube

In [38]:
df_all.to_pickle('data.pkl.gz', compression='gzip')